### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Bobur-kobilov** [0xProject/0x-codesandbox#5]
Hello! After installing node module and starting the server with "npm start", I got the following error:
(40,13): Use built-in equivalent

Thank you!!

**Comment by fabioberger** [comment]
@Bobur-kobilov are you running this code outside of the code sandbox?

**Comment by dekz** [comment]
@Bobur-kobilov ah looks like the new linter settings have been picked up in your install.

Did you install with `yarn install`?
